url: https://pubinv.github.io/chaos-pendulum
repourl: https://github.com/PubInv/chaos-pendulum
projecttitle: "Chaos Pendulum"
featuretitle: "Chaos Pendulum"
featurelink: https://pubinv.github.io/PubInv